version: "3.9"
services:
  postgres:
    image: postgres:13
    container_name: yana_pg
    environment:
      POSTGRES_USER: yanapure_app
      POSTGRES_PASSWORD: admin@yanapure
      POSTGRES_DB: yanapure
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yanapure_app -d yanapure" ]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: yana_app
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Force docker profile
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  pgdata:
